@Host = https://localhost
@Port = 7210

@StockManager_HostAddress = https://localhost:7210

GET {{StockManager_HostAddress}}/api/products
Authorization: Bearer {{Token}}
Accept: application/json

###


// already using swagger