trigger:
- main
- development

pool:
  vmImage: ubuntu-latest

steps:

# unit tests
- task: DotNetCoreCLI@2
  displayName: 'Run unit tests'
  inputs: 
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--logger trx --filter "Category!=IntegrationTests"'
    publishTestResults: false

# tests
- task: PublishTestResults@1
  displayName: 'Publish test results'
  inputs:
    testResultsFormat: VSTest
    testResultsFiles: '**/*.trx'
    testRunTitle: 'Unit tests results'
    publishRunAttachments: true

# azure login with shell
- task: AzureCLI@2
  displayName: 'Login to Azure (OIDC)'
  inputs: 
    azureSubscription: 'azure-oidc-conn'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
        echo "logged in."

# integration tests
- task: DotNetCoreCLI@2
  displayName: 'Run integration tests (KV)'
  env:
    KEYVAULT_URI: 'https://stockmanager-keyvault.vault.azure.net/'
  inputs:
    command: test
    projects: 'StockManager.Tests/StockManager.Tests.csproj'
    arguments: '--logger trx --filter "Category=IntegrationTests"'

# check sensitive data 
- script: dotnet script Azure/Scripts/CheckSecrets.csx
  displayName: 'Scan code for obvious secrets'
  continueOnError: false 

# generate report 
- script: dotnet script Azure/Scripts/CheckSecrets.csx
  displayName: 'Run script to find sensitive data in code'
